services:
  mysql:
    image: mysql:8.0
    container_name: backend-go-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: backend-go
    ports:
      - '3308:3306' # host port 3306 used for local so use 3308 for docker in host
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: