server:
  port: 8080
mysql:
  host: localhost
  port: 3308
  user: root
  password: admin
  dbName: backend-go
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  level: debug
  filename: "./storages/logs/dev.001.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 28
  compress: true
redis:
  host: localhost
  port: 6381
  password: ""
  database: 0