server:
  port: 8080
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  dbName: backend-go
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  level: debug
  filename: "./storages/logs/dev.001.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 28
  compress: true